### ISSUE TITLE
Why await Firebase?

### ISSUE THREAD

**Issue by ehzro3** [CaptainCodeman/sveltekit-example#13]
Hi!
I don't quite understand why there are `async`/`await` in some code.

For example in:
```typescript
// auth.ts
  async function signInWith(name: string) {
    const auth = getAuth(app)
    const provider = providerFor(name)
    await signInWithRedirect(auth, provider)
  }

  async function signOut() {
    const auth = getAuth(app)
    await _signOut(auth)
  }
```

What are the roles for those `async`/`await`?

**Comment by CaptainCodeman** [comment]
They are async methods, hence the await - it's just good practice IMO in case something needs to be added after them (e.g. after logout is complete, then ...)

Also, the original version lazy-loaded the older CDN based SDK so the functions were async to also wait for the scripts to load on demand.
