### ISSUE TITLE
No actually updating Firestore

### ISSUE THREAD

**Issue by Schmell** [CaptainCodeman/sveltekit-example#20]
When signing in, this does not actually add the `user` collection or a user document in Firestore.  
( I only tried in the emulator, so far )

**Comment by CaptainCodeman** [comment]
It isn't meant to- they are added to the user accounts, part of firebase auth. You can [use triggers with cloud functions to react to a new user being created](https://firebase.google.com/docs/functions/auth-events) which could include creating a record in firestore, or you might decide to do this in response to auth state changes from the client. But it's something _you_ have to chose to do for your app.
