### ISSUE TITLE
Not working on deplying with vercel

### ISSUE THREAD

**Issue by blksmr** [CaptainCodeman/sveltekit-example#21]
So i added the vercel-adapter and deployed it and i get error on /session (internal error)
![image](https://user-images.githubusercontent.com/61893697/223823500-58e11261-0baf-4ea4-b9e6-845a0ae991d3.png)

nothing more, can't figure out whats happening

**Comment by RickRyan26** [comment]
You'll want to look at Vercel's live function logs for this build, and then trigger the error to see what is logging to the server

**Comment by blksmr** [comment]
oh yeah sorry i forgot to show that log. ty vm
here it is
![image](https://user-images.githubusercontent.com/61893697/223831685-bbb1a61c-4c04-49d4-b548-2d7c79b99d5b.png)
guess there is something i don't understand about the firebase token and project id name in admin.server

**Comment by CaptainCodeman** [comment]
You need to use an actual firebase project id. The "demo" one is only valid when used with the emulator.

**Comment by blksmr** [comment]
Exactly what i did but still getting 'Error: Firebase ID token has invalid signature. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.'
