### ISSUE TITLE
svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module.

### ISSUE THREAD

**Issue by quantuminformation** [CaptainCodeman/sveltekit-example#5]
See https://kit.svelte.dev/docs#configuration for an example
No "exports" main defined in /Users/nikos/WebstormProjects/sveltekit-example/node_modules/@sveltejs/adapter-node/package.json

**Comment by CaptainCodeman** [comment]
This isn't intended to be a starter kit or runnable project, it's just to illustrate some ideas and approaches.

Anyone looking at it should be capable of handling updating between versions of SvelteKit, especially while it's still in development.

**Comment by quantuminformation** [comment]
cool
