### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Crenshinibon** [CaptainCodeman/sveltekit-example#6]
Hi. This is almost what I was looking for. Could you please add examples for unit testing and e2e testing with the Firebase emulators.

That would be really great. I've not been able to get it working ... so far ... and since SvelteKit is pretty new, haven't found any other examples.

**Comment by CaptainCodeman** [comment]
This is more of a firebase thing than something that needs a svelte example, there are instructions on how to do it:
https://firebase.google.com/docs/emulator-suite/connect_auth#instrumentauth
