### ISSUE TITLE
Error when app is launched

### ISSUE THREAD

**Issue by ivanddm** [CaptainCodeman/sveltekit-example#8]
Hi and thanks a lot for this example, it helps a lot.

I'm getting `window is not defined` `ReferenceError` when the app is first launched with `npm run dev`, both in the terminal and the browser. However, after refreshing the app it loads as expected:

![image](https://user-images.githubusercontent.com/20104703/133844558-bbbe1a41-14f4-40b6-80c8-5c2e3bbfc23f.png)

Any idea what is causing this error?

**Comment by ivanddm** [comment]
It looks like the issue is caused by firing `getAuth(app)` without checking whether the app is being run in the browser or not.

If I change line 14 in `auth.ts` to the following, the error disappears:

```javascript
const auth = browser && getAuth(app)
```

I'm closing this issue as that works as a solution for me. Thanks again!

**Comment by CaptainCodeman** [comment]
Thanks - I think I introduced this bug updating it to the v9 client SDK
